config/routes.rb
Rails.application.routes.draw do
  resources :other_models
  resources :primary_models
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/other_model.rb
class OtherModel < OtherRecord
end

app/models/other_record.rb
class OtherRecord < ApplicationRecord
  self.abstract_class = true

  connects_to database: { writing: :other }
end

app/models/primary_model.rb
class PrimaryModel < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/other_models_controller.rb
class OtherModelsController < ApplicationController
  before_action :set_other_model, only: %i[ show edit update destroy ]

  # GET /other_models or /other_models.json
  def index
    @other_models = OtherModel.all
  end

  # GET /other_models/1 or /other_models/1.json
  def show
  end

  # GET /other_models/new
  def new
    @other_model = OtherModel.new
  end

  # GET /other_models/1/edit
  def edit
  end

  # POST /other_models or /other_models.json
  def create
    @other_model = OtherModel.new(other_model_params)

    respond_to do |format|
      if @other_model.save
        format.html { redirect_to @other_model, notice: "Other model was successfully created." }
        format.json { render :show, status: :created, location: @other_model }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @other_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /other_models/1 or /other_models/1.json
  def update
    respond_to do |format|
      if @other_model.update(other_model_params)
        format.html { redirect_to @other_model, notice: "Other model was successfully updated." }
        format.json { render :show, status: :ok, location: @other_model }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @other_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /other_models/1 or /other_models/1.json
  def destroy
    @other_model.destroy
    respond_to do |format|
      format.html { redirect_to other_models_url, notice: "Other model was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_other_model
      @other_model = OtherModel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def other_model_params
      params.require(:other_model).permit(:name)
    end
end

app/controllers/primary_models_controller.rb
class PrimaryModelsController < ApplicationController
  before_action :set_primary_model, only: %i[ show edit update destroy ]

  # GET /primary_models or /primary_models.json
  def index
    @primary_models = PrimaryModel.all
  end

  # GET /primary_models/1 or /primary_models/1.json
  def show
  end

  # GET /primary_models/new
  def new
    @primary_model = PrimaryModel.new
  end

  # GET /primary_models/1/edit
  def edit
  end

  # POST /primary_models or /primary_models.json
  def create
    @primary_model = PrimaryModel.new(primary_model_params)

    respond_to do |format|
      if @primary_model.save
        format.html { redirect_to @primary_model, notice: "Primary model was successfully created." }
        format.json { render :show, status: :created, location: @primary_model }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @primary_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /primary_models/1 or /primary_models/1.json
  def update
    respond_to do |format|
      if @primary_model.update(primary_model_params)
        format.html { redirect_to @primary_model, notice: "Primary model was successfully updated." }
        format.json { render :show, status: :ok, location: @primary_model }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @primary_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /primary_models/1 or /primary_models/1.json
  def destroy
    @primary_model.destroy
    respond_to do |format|
      format.html { redirect_to primary_models_url, notice: "Primary model was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_primary_model
      @primary_model = PrimaryModel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def primary_model_params
      params.require(:primary_model).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/other_models_helper.rb
module OtherModelsHelper
end

app/helpers/primary_models_helper.rb
module PrimaryModelsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Deadlock61</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/other_models/_form.html.erb
<%= form_with(model: other_model) do |form| %>
  <% if other_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(other_model.errors.count, "error") %> prohibited this other_model from being saved:</h2>

      <ul>
        <% other_model.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/other_models/edit.html.erb
<h1>Editing Other Model</h1>

<%= render 'form', other_model: @other_model %>

<%= link_to 'Show', @other_model %> |
<%= link_to 'Back', other_models_path %>

app/views/other_models/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Other Models</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @other_models.each do |other_model| %>
      <tr>
        <td><%= other_model.name %></td>
        <td><%= link_to 'Show', other_model %></td>
        <td><%= link_to 'Edit', edit_other_model_path(other_model) %></td>
        <td><%= link_to 'Destroy', other_model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Other Model', new_other_model_path %>

app/views/other_models/new.html.erb
<h1>New Other Model</h1>

<%= render 'form', other_model: @other_model %>

<%= link_to 'Back', other_models_path %>

app/views/other_models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @other_model.name %>
</p>

<%= link_to 'Edit', edit_other_model_path(@other_model) %> |
<%= link_to 'Back', other_models_path %>

app/views/primary_models/_form.html.erb
<%= form_with(model: primary_model) do |form| %>
  <% if primary_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(primary_model.errors.count, "error") %> prohibited this primary_model from being saved:</h2>

      <ul>
        <% primary_model.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/primary_models/edit.html.erb
<h1>Editing Primary Model</h1>

<%= render 'form', primary_model: @primary_model %>

<%= link_to 'Show', @primary_model %> |
<%= link_to 'Back', primary_models_path %>

app/views/primary_models/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Primary Models</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @primary_models.each do |primary_model| %>
      <tr>
        <td><%= primary_model.name %></td>
        <td><%= link_to 'Show', primary_model %></td>
        <td><%= link_to 'Edit', edit_primary_model_path(primary_model) %></td>
        <td><%= link_to 'Destroy', primary_model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Primary Model', new_primary_model_path %>

app/views/primary_models/new.html.erb
<h1>New Primary Model</h1>

<%= render 'form', primary_model: @primary_model %>

<%= link_to 'Back', primary_models_path %>

app/views/primary_models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @primary_model.name %>
</p>

<%= link_to 'Edit', edit_primary_model_path(@primary_model) %> |
<%= link_to 'Back', primary_models_path %>